name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cross
        run: cargo install cross

      - name: Build for ${{ matrix.target }}
        run: cross build --release --target ${{ matrix.target }}

      - name: Package Binaries
        run: |
          if [[ "${{ matrix.target }}" == "x86_64-pc-windows-msvc" ]]; then
            zip yourbinary-${{ matrix.target }}.zip target/${{ matrix.target }}/release/yourbinary.exe
          else
            tar -czvf yourbinary-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release yourbinary
          fi
        shell: bash

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tjq-*.tar.gz
            tjq-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
